baseURL = "https://anderthehorizon.online"
languageCode = "en-us"
title = "Ander_The_Horizon"
copyright = "Copyright © 2024 Andrés Ospina. "
theme = "mainroad"

[params]
    author = "Andrés Ospina"
[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"

  widgets = ["search", "recent", "categories", "taglist"]
